package tenios.autotests.tests;

import tenios.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class TeniosTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("UI tests of TENIOS web site")
    void generatedTest() {
        step("Open https://www.tenios.de/", () -> {
            step("// todo: just add selenium action");
        });

        step("Set", () -> {
            step("// todo: just add selenium action");
        });

        step("Set", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.tenios.de/'", () ->
            open("https://www.tenios.de/"));

        step("Page title should have text 'TENIOS | 0800 & Geo-Rufnummern, IVR, Voice-API, Sprachbots, ACD'", () -> {
            String expectedTitle = "TENIOS | 0800 & Geo-Rufnummern, IVR, Voice-API, Sprachbots, ACD";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.tenios.de/'", () ->
            open("https://www.tenios.de/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}